# Workflows that syncs secrets across mutilple repositories

name: Sync
on:
#   push:
#   schedule:
#     - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: google/secrets-sync-action@v1.6.0
      with:
          SECRETS: |
            ^COW_1$
            ^COW_2$
          REPOSITORIES: |
            ^ksato22/secret_test_(.*)
#           DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      env:
        COW_1: ${{ secrets.COW_1 }}
        COW_2: ${{ secrets.COW_2 }}

