# Workflows that syncs secrets across mutilple repositories

name: Sync
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: google/secrets-sync-action@v1.6.0
      with:
          SECRETS: |
            ^FOO$
            ^GITHUB_.*
          REPOSITORIES: |
            ${{github.repository}}
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_SECRETS }}
          GITHUB_API_URL: ${{ secrets.CUSTOM_GITHUB_API_URL }}
          CONCURRENCY: 10
      env:
        FOO: ${{github.run_id}}
        FOOBAR: BAZ

