# Workflows that syncs secrets across mutilple repositories

name: Sync
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: google/secrets-sync-action@v1.6.0
      with:
          SECRETS: |
            ^FOO$
          REPOSITORIES: |
            ^ksato22/secret_test_1$
          github-token: ${{ secrets.GITHUB_TOKEN}}
