# Workflows that syncs secrets across mutilple repositories

name: Sync
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.6.0
        name: Sync Secrets
        with:
          SECRETS: |
            ^SUPER_
          REPOSITORIES: |
            ^secret_test_
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         env:
#           SYNCED_RUN_ID: ${{github.run_id}}
#           SYNCED_GITHUB_TOKEN_REPO: ${{secrets.GITHUB_TOKEN_REPO}}
